image: node:12.16.1
options:
  max-time: 10
pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run build:prod
